# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfata.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
import cv2 as cv


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        self.main_window = MainWindow

        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1041, 672)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Filename pentru imagine si copia ei
        self.filename = None
        self.tmp = None

        # Widget-uri
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(40, 460, 661, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        '''contrast Slider'''
        self.contrastSlider = QtWidgets.QSlider(self.centralwidget)
        self.contrastSlider.setGeometry(QtCore.QRect(750, 70, 160, 22))
        self.contrastSlider.setOrientation(QtCore.Qt.Horizontal)
        self.contrastSlider.setObjectName("contrastSlider")
        self.contrastSlider.setMinimum(50)
        self.contrastSlider.setMaximum(150)
        self.contrastSlider.setValue(100)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(770, 50, 141, 16))
        self.label.setObjectName("label")

        '''Imagine'''
        self.Imagine = QtWidgets.QLabel(self.centralwidget)
        self.Imagine.setGeometry(QtCore.QRect(20, 10, 681, 441))
        self.Imagine.setObjectName("Imagine")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1041, 26))
        self.menubar.setObjectName("menubar")

        '''Meniu'''
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        '''Buton'''
        self.DetectButton = QPushButton(self.centralwidget)
        self.DetectButton.setObjectName(u"DetectButton")
        self.DetectButton.setGeometry(QtCore.QRect(810, 520, 111, 31))

        '''Gamma slider'''
        self.GammaSlider = QSlider(self.centralwidget)
        self.GammaSlider.setObjectName(u"GammaSlider")
        self.GammaSlider.setGeometry(QRect(750, 160, 160, 22))
        self.GammaSlider.setOrientation(Qt.Horizontal)
        self.GammaSlider.setMinimum(1)
        self.GammaSlider.setMaximum(2)

        '''Gamma label'''
        self.GammaLabel = QLabel(self.centralwidget)
        self.GammaLabel.setObjectName(u"GammaLabel")
        self.GammaLabel.setGeometry(QRect(810, 140, 55, 16))


        self.contrastSlider.raise_()
        self.label.raise_()
        self.line.raise_()
        self.Imagine.raise_()
        self.DetectButton.raise_()
        self.GammaSlider.raise_()
        self.GammaLabel.raise_()

        '''Aici se creeaza actiunile'''

        self.actionNou = QtWidgets.QAction(MainWindow)
        self.actionNou.setObjectName("actionNou")

        self.action_sterge = QtWidgets.QAction(MainWindow)
        self.action_sterge.setObjectName("action_sterge")

        self.actionContrast = QtWidgets.QAction(MainWindow)
        self.actionContrast.setObjectName("actionContrast")

        self.menuFile.addAction(self.actionNou)
        self.menuFile.addAction(self.action_sterge)
        self.menubar.addAction(self.menuFile.menuAction())
        self.contrastSlider.addAction(self.actionContrast)


        self.retranslateUi(MainWindow)

        #Aici se conecteaza actiunile la sloturi
        self.actionNou.triggered.connect(self.loadImage)  # Conectează la metoda loadImage
        self.action_sterge.triggered.connect(self.deletePhoto)

        self.contrastSlider.valueChanged['int'].connect(self.setContrast)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    '''Sfarsit setupUi'''

    def defaultValues(self):
        self.contrastSlider.setValue(100)
    def loadImage(self):

        self.filename = QFileDialog.getOpenFileName(directory="G:/__PI Proiect/pythonProject1/res/images",filter="Image (*.png *.jpg *.jpeg *.bmp)")[0]
        self.defaultValues()
        if self.filename:
            self.image = cv.imread(self.filename)
            if self.image is None:
                QMessageBox.warning(self.main_window, "Eroare",
                                    "Imaginea nu a putut fi încărcată. Verifică dacă fișierul este valid.")
                return

            self.tmp = self.image.copy()
            self.setPhoto(self.image)

    '''Sfarsit loadImage'''
    def setPhoto(self, image):
        image = cv.resize(image, [681, 441], interpolation=cv.INTER_AREA)
        frame = cv.cvtColor(image, cv.IMREAD_ANYCOLOR)
        image = QImage(frame, frame.shape[1], frame.shape[0], frame.strides[0], QImage.Format_RGB888)

        self.Imagine.setPixmap(QtGui.QPixmap.fromImage(image))

    def deletePhoto(self):
        self.Imagine.setText("Încarcă o imagine pentru a începe.")


    def setContrast(self):
        if self.tmp is None:
            return

        value = self.contrastSlider.value() / 100.0

        #newImage = cv.convertScaleAbs(self.tmp, alpha=1+value, beta=0)

        newImage = cv.addWeighted(self.tmp, value, self.tmp, 0, 0.8)
        self.setPhoto(newImage)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DeepFrame"))
        self.label.setText(_translate("MainWindow", "Îmbunătățire contrast"))
        self.Imagine.setText(_translate("MainWindow", "Încarcă o imagine pentru a începe."))
        self.menuFile.setTitle(_translate("MainWindow", "Fișier"))
        self.actionNou.setText(_translate("MainWindow", "Nou"))
        self.action_sterge.setText(_translate("MainWindow", "Șterge fișierul"))
        self.DetectButton.setText(QCoreApplication.translate("MainWindow", u"Detecție obiecte", None))
        self.GammaLabel.setText(QCoreApplication.translate("MainWindow", u"Gamma", None))



# if __name__ == "__main__":
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())